version: '3.7'
services:
  postgres:
    container_name: inasaku_postgres
    build: ./postgres
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: ./spring
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    tty: true
    volumes:
      - ../spring:/srv
    working_dir: /srv

  frontend:
    container_name: frontend
    build: ./vue
    ports:
      - '8081:8080'
    volumes:
      - ../vue:/usr/src/app
    stdin_open: true
    tty: true


